//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Base_Book
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Author { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> PYear { get; set; }
        public string BookName { get; set; }
        public string Version { get; set; }
        public string Pic { get; set; }
    }
}
